{
  config,
  custom_vars,
  pkgs,
  ...
}: let
  rofiFont = "${custom_vars.FONT} Bold 10";
  rofiTerminal = "${pkgs.kitty}/bin/kitty";
  themeName = "style.rasi";
  themePath = "${config.xdg.configHome}/rofi/${themeName}";
  rofiConfDir = "~/.config/rofi";
in {
  programs.rofi = {
    enable = true;
    package = pkgs.rofi-wayland;
    font = rofiFont;
    terminal = rofiTerminal;

    modes = ["drun" "run" "filebrowser" "window" "emoji"];
    plugins = [pkgs.rofi-emoji-wayland];

    location = "center";
    cycle = true;

    extraConfig = {
      show-icons = true;
      display-drun = " ";
      display-run = " ";
      display-filebrowser = " ";
      display-window = " ";
      display-emoji = " ";
      drun-display-format = "{name}";
      window-format = "{w} · {c} · {t}";
    };

    theme = themePath;
  };

  # Fonts include
  "xdg".configFile."rofi/fonts.rasi".text = ''
    * { font: "${rofiFont}"; }
  '';

  "xdg".configFile."rofi/style.rasi".text = ''
    /* includes */
    /* Generated by Wallust */

    @import "${rofiConfDir}/rofi-colors-transparent.rasi"

    @import "${rofiConfDir}/fonts.rasi"

    /* Window ----------------------------------------- */
    window {
      fullscreen:                 false;
      transparency:               "real";
      cursor:                     "default";
      background-color:           black / 85%;
      border-color:               @selected;
      location:                   center;
      anchor:                     center;
      border:                     1px;
      border-radius:              15px;
      width:                      55%;
    }

    /* Main Box ---------------------------------------- */
    mainbox {
      children:                   [ "img", "listbox"];
      orientation:                horizontal;
      background-color:           transparent;
      padding:                    14px;
      spacing:                    24px;
    }

    /* Image ------------------------------------------- */
    img {
      border-radius:              15px;
      background-color:           transparent;
      background-image:           url("${custom_vars.CACHE_PATH}/current_wallpaper", height);
    }

    /* Listbox ----------------------------------------- */
    listbox {
      spacing:                     25px;
      background-color:            transparent;
      orientation:                 vertical;
      children:                    [ "inputbar", "message", "listview", "mode-switcher" ];
    }

    /* Listview ---------------------------------------- */
    listview {
      columns:                     1;
      lines:                       6;
      cycle:                       true;
      dynamic:                     true;
      scrollbar:                   false;
      layout:                      vertical;
      reverse:                     false;
      fixed-height:                true;
      fixed-columns:               true;
      border:                      0px;
      spacing:                     16px;
      background-color:            transparent;
    }

    /* Mode Switcher ----------------------------------- */
    mode-switcher{
      enabled:                     true;
      spacing:                     20px;
      background-color:            transparent;
      text-color:                  @foreground;
    }
    button {
      padding:                     15px;
      border-radius:               10px;
      background-color:            @background-alt;
      text-color:                  inherit;
      cursor:                      pointer;
    }
    button selected {
      background-color:            @selected;
      text-color:                  @foreground;
    }

    /* Inputbar ---------------------------------------- */
    inputbar {
      children:                    [ "textbox-icon", "entry" ];
      border-radius:               12px;
      background-color:            white / 20%;
      text-color:                  @foreground;
      spacing:                     0px;
      margin:                      0px;
      padding:                     14px;
    }

    textbox-icon {
      expand:                      false;
      background-color:            transparent;
      text-color:                  inherit;
      str: "  ";
    }

    /* Entry ------------------------------------------- */
    entry {
      cursor:                     text;
      expand:                     false;
      placeholder-color:          inherit;
      placeholder:                "Search....";
      background-color:           transparent;
      text-color:                 inherit;
    }

    /* Elements ---------------------------------------- */
    element {
      cursor:                     pointer;
      spacing:                    15px;
      background-color:           transparent;
      border-radius:              10px;
      padding:                    12px;
    }

    element-text {
      vertical-align:              0.5;
      cursor:                      inherit;
      background-color:            transparent;
      text-color:                  inherit;
    }

    element-icon {
      size:                        30px;
      cursor:                      inherit;
      background-color:            transparent;
      text-color:                  inherit;
    }

    element normal.normal,
    element alternate.normal {
      background-color:            transparent;
      text-color:                  @foreground;
    }

    element selected.normal {
      background-color:            white / 18%;
      text-color:                  white;
      border:                      2px solid;
      border-color:                @selected;
    }

    /* Scrollbar --------------------------------------- */
    scrollbar {
      margin:                      0px 4px;
      handle-width:                8px;
      handle-color:                white;
      background-color:            white / 10%;
      border-radius:               4px;
    }

    /* Message ----------------------------------------- */
    message {
      background-color:            white / 16%;
      border:                      1px solid;
      border-color:                transparent;
      border-radius:               12px;
      padding:                     24px;
    }
    error-message {
      padding:                     100px;
      border:                      0px solid;
      border-radius:               0px;
      background-color:            black / 14%;
      text-color:                  @foreground;
    }
    textbox {
      background-color:            transparent;
      text-color:                  @foreground;
      vertical-align:              0.5;
      horizontal-align:            0.5;
      highlight:                   none;
    }
  '';
}
